import "./index.css";
var a = 1;
var b = 2;
var c = 3;
var d = 4;
var e = 5;
console.log(a, b, c, d, e, dd);
var dd = 5;
var test;
console.log(test);
var h1 = document.createElement("h1");
h1.innerText = "h1";
document.body.appendChild(h1);
var h2 = document.createElement("h2");
h2.innerText = "h2";
document.body.appendChild(h2);
var h3 = document.createElement("h3");
h3.innerText = "h3";
document.body.appendChild(h3);
